disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
opt_in_rules:
- empty_count
included:
- Sources
- Tests
excluded:
- Carthage
- Pods
- vendor
- Tests/MurrayKitTests/Mocks

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error # implicitly
force_try:
  severity: error # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 155
function_body_length: 60
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 300
  error: 700
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
nesting:
  type_level: 3
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - to
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

