disabled_rules:
- trailing_whitespace
- blanket_disable_command
opt_in_rules:
- empty_count
included:
- Sources
- Tests
excluded:
- Tests/MurrayKitTests/Mocks

force_cast: error # implicitly
force_try:
  severity: error # explicitly

line_length: 155
function_body_length: 80

type_body_length:
  warning: 300 
  error: 400
file_length:
  warning: 300
  error: 700
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
nesting:
  type_level: 3
identifier_name:
  min_length: 
    error: 2 
  excluded:
    - id
    - URL
    - to
reporter: "xcode"

