name: MurrayKit Tests

on:
  pull_request: {}

jobs:
  TestMurrayKit:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: swiftlint lint --strict
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test 2>&1 | xcpretty
  TestLinux:
    runs-on: ubuntu-latest
    container: swift:5.3
    steps:
      - uses: actions/checkout@v2
      - name: Resolve
        run: swift package resolve
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test 2>&1
